#!/bin/bash
#PBS -l nodes=1:ppn=1,vmem=16gb,walltime=1:00:00
#PBS -N roiMerge
#PBS -V

echo "merging ROIs"
time singularity exec -e docker://brainlife/afni:16.3.0 ./roiMerge.sh

# if [ ! -f ./parc/parc.nii.gz ]; then
#     echo "something failed. please check logs and derivatives"
#     exit 1
# else
#     exit 0
# fi
